providers = ["php"]

[phases.setup]
nixPkgs = ["(php.withExtensions (pe: pe.enabled ++ []))", "nginx", "libmysqlclient", "phpPackages.composer", "nodejs_20", "npm-10_x"]
nixLibs = ["libmysqlclient"]
nixOverlays = ["https://github.com/railwayapp/nix-npm-overlay/archive/main.tar.gz"]

[phases.install]
cmds = ["composer install --no-dev --optimize-autoloader && npm install"]

[phases.build]
cmds = ["npm run build"]
