providers = ["php", "node"]

[variables]
NIXPACKS_NODE_VERSION = "20"

[phases.install]
cmds = ["composer install --no-dev --optimize-autoloader", "rm -rf node_modules package-lock.json", "npm install"]
