providers = ["php"]

[phases.setup]
nixPkgs = ["(php.withExtensions (pe: pe.enabled ++ []))", "nginx", "libmysqlclient", "phpPackages.composer", "nodejs_20", "npm-10_x"]
nixLibs = ["libmysqlclient"]
nixOverlays = ["https://github.com/railwayapp/nix-npm-overlay/archive/main.tar.gz"]

[phases.install]
cmds = ["composer install --no-dev --optimize-autoloader && npm install"]

[phases.build]
cmds = ["npm run build"]

[start]
cmd = "mkdir -p /var/log/nginx && node /assets/scripts/prestart.mjs /assets/nginx.template.conf /nginx.conf && (php-fpm -y /assets/php-fpm.conf & nginx -c /nginx.conf)"
